version: '3.5'

services:
  postgres:
    container_name: authorization_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=authorization
    image: postgres:13.11-bullseye
    ports:
      - '5432:5432'
    volumes:
      - authorization:/var/lib/postgresql/authorization

volumes:
  authorization: