version: '3.5'

services:
  authorization:
    container_name: authorization_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=authorization
    image: postgres:13.11-bullseye
    ports:
      - '5432:5432'
    volumes:
      - authorization:/var/lib/postgresql/authorization
  file-manager:
    container_name: file_manager_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=file_manager
    image: postgres:13.11-bullseye
    ports:
      - '5433:5432'
    volumes:
      - file_manager:/var/lib/postgresql/file_manager

volumes:
  authorization:
  file_manager: