version: '3.5'

services:
  authorization:
    container_name: authorization_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=authorization
    image: postgres:13.11-bullseye
    ports:
      - '5432:5432'
    volumes:
      - authorization:/var/lib/postgresql/authorization
  file-manager:
    container_name: file_manager_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=file_manager
    image: postgres:13.11-bullseye
    ports:
      - '5433:5432'
    volumes:
      - file_manager:/var/lib/postgresql/file_manager
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
#    environment:
#      - KAFKA_ENABLE_KRAFT=yes
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#      - KAFKA_BROKER_ID=1
#      - KAFKA_NODE_ID=1
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CFG_NODE_ID=0
    volumes:
      - kafka:/var/lib/kafka
#  authorization-microservice:
#    container_name: authorization-microservice
#    build:
#      context: ./authorization-microservice
#    depends_on:
#      - kafka
#    ports:
#      - "9200:9200"
#    environment:
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://authorization_db:5432/authorization
#      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#  file_manager:
#    container_name: file_manager
#    build:
#      context: ./file_manager
#    depends_on:
#      - kafka
#    ports:
#      - "9000:9000"
#    environment:
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://file_manager_db:5432/file_manager
#      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#      - SERVICE_AUTHENTICATION_IS-AUTHENTICATION_URL=http://authorization-microservice:9200/api/authentication/micro-service/is-authentication

volumes:
  authorization:
  file_manager:
  kafka: