services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/data:/var/log/nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
