### request create user
POST http://localhost:8080/api/v1/auth/service/signup
Content-Type: application/json

{
  "login": "kamegatze",
  "password": "t62241299A",
  "firstName": "Al",
  "lastName": "Sh",
  "email": "aleksi.aleksi2014@yandex.ru"
}

### request signin user
POST http://localhost:8080/api/v1/auth/service/signin
Content-Type: application/json

{
  "login": "kamegatze",
  "credentials": "t62241299A"
}

### request about user
GET localhost:8080/api/v1/auth/service/info-user-by-login?login=kamegatze
Content-Type: application/json

### check is authentication user or not
GET localhost:8080/api/v1/auth/service/is-authentication
Content-Type: application/json
Authorization: Bearer
AuthorizationRefresh:

### check is authentication via response code 200 is authentication 401 is not authentication
GET localhost:8080/api/v1/auth/service/is-authentication-via-response-code
Content-Type: application/json
Authorization: Bearer
AuthorizationRefresh:

### request update access token
GET localhost:8080/api/v1/auth/service/authentication
Content-Type: application/json
Authorization: Bearer
AuthorizationRefresh:

### generate qr-code and code for 2fa
GET localhost:8080/api/v1/account/set-2fa-authentication
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRob3JpemF0aW9uLWZpbGUtbWFuYWdlciIsInN1YiI6ImthbWVnYXR6ZSIsImV4cCI6MTczNjE4MDY0NSwiaWF0IjoxNzM2MTc4ODQ1LCJhdXRob3JpdHkiOiJBVVRIT1JJVFlfUkVBRCAifQ.DF4uYYkymJMVMVcs5i-LF31g_9kRnwNqXaop2RcOp7JbKoG6aLmgwSODnzbZwdX-1M7f3A21L5meN4cfnUMlAvfO3l70PSpuDAK2MC8wb8_eUbQrk_CTC7cB0E7nLaheAegAnIf4z0Js5_7hv88eU7O87U4qK2J2itkQ-quRNGkAaQJ9F1Sl3d6TLgMlcNwvqD9B6N3fO_50zuSyr1l1GQVfq4Bm1QMTZDobL41bHvxpm2uNepv73-mUneBc7kqP9hF4bTCvFPxMJ1tN7JCkMy-bQsOQh7tRmHi2x4ayCae3naIgJ_twIvF6sLnsLHCNR4kr7Ncgnq172OwHP_-PNQ

### set user authentication via 2fa
GET localhost:8080/api/v1/account/save-2fa-authentication?code=960275
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRob3JpemF0aW9uLWZpbGUtbWFuYWdlciIsInN1YiI6ImthbWVnYXR6ZSIsImV4cCI6MTczNjE4MDY0NSwiaWF0IjoxNzM2MTc4ODQ1LCJhdXRob3JpdHkiOiJBVVRIT1JJVFlfUkVBRCAifQ.DF4uYYkymJMVMVcs5i-LF31g_9kRnwNqXaop2RcOp7JbKoG6aLmgwSODnzbZwdX-1M7f3A21L5meN4cfnUMlAvfO3l70PSpuDAK2MC8wb8_eUbQrk_CTC7cB0E7nLaheAegAnIf4z0Js5_7hv88eU7O87U4qK2J2itkQ-quRNGkAaQJ9F1Sl3d6TLgMlcNwvqD9B6N3fO_50zuSyr1l1GQVfq4Bm1QMTZDobL41bHvxpm2uNepv73-mUneBc7kqP9hF4bTCvFPxMJ1tN7JCkMy-bQsOQh7tRmHi2x4ayCae3naIgJ_twIvF6sLnsLHCNR4kr7Ncgnq172OwHP_-PNQ
