token:
  cookie:
    jwt:
      access-token:
        name: access-token
        path: /
        domain: localhost
        max-age: ${app.access-token}
        http-only: true
        secure: false
        sameSite: Strict
      refresh-token:
        name: refresh-token
        path: /
        domain: localhost
        max-age: ${app.access-token}
        http-only: true
        secure: false
        sameSite: Strict

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8081/eureka

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://authorization-file-manager:5432/authorization

  kafka:
    bootstrap-servers: kafka-file-manager:29092