server:
  port: 9200

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://dev-server-kamegatze:5434/authorization

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true

  graphql:
    graphiql:
      enabled: true

  kafka:
    bootstrap-servers: dev-server-kamegatze:29092
    topics:
      save:
        users: save-users

  application:
    name: authorization-microservice

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

logging:
  level:
    org:
      springframework:
        security: info

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

app:
  name-application: authorization-file-manager
  access-token: 30
  refresh-token: 1440

springdoc:
  api-docs:
    path: '/${spring.application.name}/v3/api-docs'
  swagger-ui:
    path: '/${spring.application.name}/swagger-ui.html'