server:
  port: 9200

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5434/authorization

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true

  graphql:
    graphiql:
      enabled: true

  kafka:
    bootstrap-servers: localhost:29092
    topics:
      save:
        users: save-users

  application:
    name: authorization-microservice

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

logging:
  level:
    org:
      springframework:
        security: debug

token:
  cookie:
    jwt:
      access-token:
        name: __Host-access-token
        path: /
        domain:
        max-age: '${app.access-token}'
        http-only: true
        secure: true
        sameSite: none
      refresh-token:
        name: __Host-refresh-token
        path: /
        domain:
        max-age: '${app.refresh-token}'
        http-only: true
        secure: true
        sameSite: none

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

app:
  name-application: authorization-file-manager
  access-token: 30
  refresh-token: 1440

springdoc:
  api-docs:
    path: '/${spring.application.name}/v3/api-docs'
  swagger-ui:
    path: '/${spring.application.name}/swagger-ui.html'