spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/authorization

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true

logging:
  level:
    org:
      springframework:
        security: trace

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

app:
  name-application: authorization-file-manager
  access-token: 30
  refresh-token: 1440