server:
  port: 8080

authorization:
  uri: http://localhost:9200/api/v1/auth/is-authentication
  routes-skip:
    - /file-manager/**
    - /authorization-microservice/**
    - /api/v1/auth/**

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  profiles:
    default: dev

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - Authorization
      routes:
        - id: authorization-microservice
          uri: http://localhost:9200
          predicates:
            - Path=/authorization-microservice/**, /api/v1/auth/**
        - id: file-manager
          uri: http://localhost:9000
          predicates:
            - Path=/file-manager/**, /api/v1/file-system/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: '/${spring.cloud.gateway.routes[0].id}/v3/api-docs'
        name: authorization service
      - url: '/${spring.cloud.gateway.routes[1].id}/v3/api-docs'
        name: file manager service