authorization:
  uri: http://authorization-microservice:9200/api/v1/auth/is-authentication

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8081/eureka

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://192.168.2.100:5173"
            allowedHeaders: "*"
            allowedMethods: "*"