server:
  port: 8080


spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  profiles:
    default: dev

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - Authorization
      routes:
        - id: authorization-microservice
          uri: lb://${spring.cloud.gateway.routes[0].id}
          predicates:
            - Path=/authorization-microservice/**, /api/v1/auth/**
        - id: file_manager
          uri: lb://${spring.cloud.gateway.routes[1].id}
          predicates:
            - Path=/file-manager/**, /api/v1/file-system/**
        - id: eureka-server
          uri: http://${spring.cloud.gateway.routes[2].id}:8081
          predicates:
            - Path=/eureka-ui, /eureka/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

authorization:
  uri: http://localhost:9200/api/v1/auth/is-authentication
  routes-skip:
    - /${spring.cloud.gateway.routes[0].id}/**
    - /${spring.cloud.gateway.routes[1].id}/**
    - /api/v1/auth/**
    - /eureka-ui/**
    - /eureka/**


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: '/${spring.cloud.gateway.routes[0].id}/v3/api-docs'
        name: authorization service
      - url: '/${spring.cloud.gateway.routes[1].id}/v3/api-docs'
        name: file manager service