eureka:
  client:
    enabled: false

spring:
  cloud:
    gateway:
      routes:
        - id: authorization-microservice
          uri: http://localhost:9200
          predicates:
            - Path=/authorization-microservice/**, /api/v1/auth/**
        - id: file-manager
          uri: http://localhost:9000
          predicates:
            - Path=/file-manager/**, /api/v1/file-system/**