### request create user
POST http://localhost:8080/api/v1/auth/service/signup
Content-Type: application/json

{
  "login": "kamegatze",
  "password": "t62241299A",
  "firstName": "Al",
  "lastName": "Sh",
  "email": "aleksi.aleksi2014@yandex.ru"
}

### request signin user
POST http://localhost:8080/api/v1/auth/service/signin
Content-Type: application/json

{
  "login": "kamegatze",
  "credentials": "t62241299A"
}

### request about user
GET localhost:8080/api/v1/auth/service/info-user-by-login?login=kamegatze
Content-Type: application/json

### check is authentication user or not
GET localhost:8080/api/v1/auth/service/is-authentication
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRob3JpemF0aW9uLWZpbGUtbWFuYWdlciIsInN1YiI6ImthbWVnYXR6ZSIsImV4cCI6MTczNjE3ODI1MywiaWF0IjoxNzM2MTc2NDUzLCJhdXRob3JpdHkiOiJBVVRIT1JJVFlfUkVBRCAifQ.m1Z8j9j9oT0Z0dcdLYQl4CcCrt8J3D-ezELJR5Ouk4aKO-19CNx3m-Gnx09dMl2fFGEdwyhFb1-24PQ0l4okbIuIqvQimTd532I5ciZW3fNZSy6Ccq0U1C1eO1GbGbpDBkuKbDchfnH6WNqLLCltRCX-HfG6UeRqSMyZ9ARvDBIIP5AdgIV7cBuWU7x_JcGexJE3cAir32dy-1abBLUaaXKtn1CBmhz8wtyIp33nwvXBBpL20GAbqgGKrPHTfEPYP1aT5I6FDaylMG27zQxxqqimIzd288IvLHh2yqg7JONYQRINnhgJLWc2nMe80B3NrM7b429naUPPYx30wJKayw
AuthorizationRefresh: eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRob3JpemF0aW9uLWZpbGUtbWFuYWdlciIsInN1YiI6ImthbWVnYXR6ZSIsImV4cCI6MTczNjI2Mjg1MywiaWF0IjoxNzM2MTc2NDUzLCJhdXRob3JpdHkiOiJBVVRIT1JJVFlfUkVBRCAifQ.JCKrwvuLzjGnYAbc_iCFtutqC99975LwglalMxvIA-9zzFIYi3KbjMQwzH_UtLE7cm9SV_LJhrx_ex9uK8n0g_tJxHaims9IEb_PTpku9CmO6laGoN2-NhvDlX4xBzEnCqs6pbOK-PFxiaPqpjyCrERG1hsJ-EoKtuVRZfxQN8ZM_SVz_L342QmFCSMZFm8saAMLKFUQ126bQDp6KcjWz26gj5nSzi8DWFdOsKSZzig5xDubF1vdK_APTroH7Dgks-WgTwGRvKUCWTzoxcnqYq1uW_YvtOSZ1J6O967wUyNDiB7fG7A2ENSAvdgnY9CqhU6M_tC6pAu9FiTNcjA1HQ

### check is authentication via response code 200 is authentication 401 is not authentication
GET localhost:8080/api/v1/auth/service/is-authentication-via-response-code
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRob3JpemF0aW9uLWZpbGUtbWFuYWdlciIsInN1YiI6ImthbWVnYXR6ZSIsImV4cCI6MTczNjE3ODI1MywiaWF0IjoxNzM2MTc2NDUzLCJhdXRob3JpdHkiOiJBVVRIT1JJVFlfUkVBRCAifQ.m1Z8j9j9oT0Z0dcdLYQl4CcCrt8J3D-ezELJR5Ouk4aKO-19CNx3m-Gnx09dMl2fFGEdwyhFb1-24PQ0l4okbIuIqvQimTd532I5ciZW3fNZSy6Ccq0U1C1eO1GbGbpDBkuKbDchfnH6WNqLLCltRCX-HfG6UeRqSMyZ9ARvDBIIP5AdgIV7cBuWU7x_JcGexJE3cAir32dy-1abBLUaaXKtn1CBmhz8wtyIp33nwvXBBpL20GAbqgGKrPHTfEPYP1aT5I6FDaylMG27zQxxqqimIzd288IvLHh2yqg7JONYQRINnhgJLWc2nMe80B3NrM7b429naUPPYx30wJKayw
AuthorizationRefresh: eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRob3JpemF0aW9uLWZpbGUtbWFuYWdlciIsInN1YiI6ImthbWVnYXR6ZSIsImV4cCI6MTczNjI2MjkzNCwiaWF0IjoxNzM2MTc2NTM0LCJhdXRob3JpdHkiOiJBVVRIT1JJVFlfUkVBRCAifQ.M5KEPZzLzyRqiomI5Q9maJMvXVeSWXUqpnKf9pjY__8-g2I4s4pTAH6eGExBas0NnzZz4tWiKgUt6oJ7M7UhjG820Mwy8921LlHDHGFNL4dow6b3g-05wy2QS29GZ-qErSQcttS_TFxcUFGYVpYgOSLBKgUh9sShxSnbdYY0IzmXlnLXalaNBfJZ8eKhywQ_GwJLWdQ63CgcKHWSHY8XZq1zG_ZFzuJYVKY7RMYLkt2C3nYO5rnJ8CkCmt_AS7mQ0YmFE0rkeXxYUmKMUKujy0aTEtxwI2gGrAF-G4he6kbW0uPzWwYwx4sp_pc_ZzQZicgrsZEbYxZ2WMUnJUfuMw

### request update access token
GET localhost:8080/api/v1/auth/service/authentication
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRob3JpemF0aW9uLWZpbGUtbWFuYWdlciIsInN1YiI6ImthbWVnYXR6ZSIsImV4cCI6MTczNjE3ODI1MywiaWF0IjoxNzM2MTc2NDUzLCJhdXRob3JpdHkiOiJBVVRIT1JJVFlfUkVBRCAifQ.m1Z8j9j9oT0Z0dcdLYQl4CcCrt8J3D-ezELJR5Ouk4aKO-19CNx3m-Gnx09dMl2fFGEdwyhFb1-24PQ0l4okbIuIqvQimTd532I5ciZW3fNZSy6Ccq0U1C1eO1GbGbpDBkuKbDchfnH6WNqLLCltRCX-HfG6UeRqSMyZ9ARvDBIIP5AdgIV7cBuWU7x_JcGexJE3cAir32dy-1abBLUaaXKtn1CBmhz8wtyIp33nwvXBBpL20GAbqgGKrPHTfEPYP1aT5I6FDaylMG27zQxxqqimIzd288IvLHh2yqg7JONYQRINnhgJLWc2nMe80B3NrM7b429naUPPYx30wJKayw
AuthorizationRefresh: eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRob3JpemF0aW9uLWZpbGUtbWFuYWdlciIsInN1YiI6ImthbWVnYXR6ZSIsImV4cCI6MTczNjI2MjkzNCwiaWF0IjoxNzM2MTc2NTM0LCJhdXRob3JpdHkiOiJBVVRIT1JJVFlfUkVBRCAifQ.M5KEPZzLzyRqiomI5Q9maJMvXVeSWXUqpnKf9pjY__8-g2I4s4pTAH6eGExBas0NnzZz4tWiKgUt6oJ7M7UhjG820Mwy8921LlHDHGFNL4dow6b3g-05wy2QS29GZ-qErSQcttS_TFxcUFGYVpYgOSLBKgUh9sShxSnbdYY0IzmXlnLXalaNBfJZ8eKhywQ_GwJLWdQ63CgcKHWSHY8XZq1zG_ZFzuJYVKY7RMYLkt2C3nYO5rnJ8CkCmt_AS7mQ0YmFE0rkeXxYUmKMUKujy0aTEtxwI2gGrAF-G4he6kbW0uPzWwYwx4sp_pc_ZzQZicgrsZEbYxZ2WMUnJUfuMw
