### get info about root
GET localhost:9000/api/v1/file-system/get-root
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRob3JpemF0aW9uLWZpbGUtbWFuYWdlciIsInN1YiI6ImthbWVnYXR6ZSIsImV4cCI6MTc0MjE1OTIyMSwiaWF0IjoxNzQyMTU3NDIxLCJhdXRob3JpdHkiOiJBVVRIT1JJVFlfUkVBRCAifQ.ZsFtMneM3YOWt_lI7paLSqpoyE9nXWntaeGcRznJxKHuwTSsjfPgsIDlsSmNWPc_0xNT4RnuIkCsjMxn1ZDey3F3n7lI_lYsgtqcUjZCPIEv044qWTe0J0v0Vur_Nvb4MCq6yhhty4fyJP59HejMiui0PwVTvwk1cpd8NE5hBbrmyh8CP5R95oJvzjC4dvPFK2FiQyU3LDMuNJRR4I_Su_FawA7x4jW__VywvwrMU-bqo-aSiUIiZnmKB9tRj3QsnP7wn1RozkD4rfwCqUitz7EtLLSiEUNer3o2bxoLQyg5MkstMg0-RvtJk7mmUeL8GDduKcnYP5oJ4pbgarN8nA

### get children
GET localhost:9000/api/v1/file-system/children?parentId=d2aae82e-2807-4e5a-9db6-ea65af958096
Content-Type: application/json
Authorization: Bearer

### get info about file or folder
GET localhost:8080/api/v1/file-system/d2aae82e-2807-4e5a-9db6-ea65af958096
Content-Type: application/json
Authorization: Bearer

### get children by path
GET localhost:8080/api/v1/file-system/children-by-path?path=/test
Content-Type: application/json
Authorization: Bearer


### create folder
POST localhost:8080/api/v1/file-system/create-folder
Content-Type: application/json
Authorization: Bearer

{
  "name": "test",
  "parentId": "d2aae82e-2807-4e5a-9db6-ea65af958096"
}