server:
  port: 8082

spring:
  application:
    name: doc-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: authorization-microservice
          uri: http://localhost:9200
          predicates:
            - Path=/authorization-microservice/**
        - id: file-manager
          uri: http://localhost:9000
          predicates:
            - Path=/file-manager/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: '/${spring.cloud.gateway.routes[0].id}/v3/api-docs'
        name: authorization service
      - url: '/${spring.cloud.gateway.routes[1].id}/v3/api-docs'
        name: file manager service