version: '3.5'

services:
  authorization-file-manager:
    container_name: authorization-file-manager
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=authorization
    image: postgres:13.11-bullseye
    networks:
      - isolated
    ports:
      - '5434'
    volumes:
      - authorization-file-manager:/var/lib/postgresql/data

  file-manager-file-system:
    container_name: file-manager-file-system
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=file_manager
    image: postgres:13.11-bullseye
    networks:
      - isolated
    ports:
      - '5433'
    volumes:
      - file-manager-file-system:/var/lib/postgresql/data

  eureka-server:
    restart: always
    container_name: eureka-server
    build:
      context: ../../eureka-server
    networks:
      - isolated
    ports:
      - "8081"
    environment:
      - spring.profiles.active=demo

  authorization-microservice:
    restart: always
    container_name: authorization-microservice
    build:
      context: ../../authorization-microservice
    depends_on:
      - kafka-file-manager
      - eureka-server
      - authorization-file-manager
    networks:
      - isolated
    ports:
      - "9200"
    environment:
      - spring.profiles.active=demo


  file_manager:
    restart: always
    container_name: file_manager
    build:
      context: ../../file_manager
    depends_on:
      - kafka-file-manager
      - eureka-server
      - file-manager-file-system
    networks:
      - isolated
    ports:
      - "9000"
    environment:
      - spring.profiles.active=demo

  gateway-service:
    restart: always
    container_name: gateway-service
    build:
      context: ../../gateway-service
    depends_on:
      - authorization-file-manager
      - file_manager
      - eureka-server
    networks:
      - isolated
      - net
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=demo


  kafka-file-manager:
    image: apache/kafka:latest
    container_name: kafka-file-manager
    restart: always
    networks:
      - isolated
    ports:
      - "29092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka-file-manager:29092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-file-manager:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

networks:
  isolated:
    internal: true
  net:
    driver: bridge

volumes:
  authorization-file-manager:
    driver: local
  file-manager-file-system:
    driver: local
  kafka_data:
    driver: local