version: '3.5'

services:
  nginx:
    restart: always
    build:
      context: ./images/nginx
    container_name: nginx
    networks:
      - isolated
      - net
    ports:
      - "8080:80"
    volumes:
      - ./nginx/certificate:/etc/nginx/certificate
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/data:/var/log/nginx
      - ./nginx/js:/etc/nginx/js

    

  authorization-file-manager:
    container_name: authorization-file-manager
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=authorization
    image: postgres:13.11-bullseye
    networks:
      - isolated
      - net
    ports:
      - '5434:5432'
    volumes:
      - ./database/authorization-file-manager/data:/var/lib/postgresql/data

  file-manager-file-system:
    container_name: file-manager-file-system
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=file_manager
    image: postgres:13.11-bullseye
    networks:
      - isolated
      - net
    ports:
      - '5433:5432'
    volumes:
      - ./database/file-manager-file-system/data:/var/lib/postgresql/data
  
  file-manager-front:
    container_name: file-manager-front
    restart: always
    build:
      context: ../../../file-manager-front
    networks:
      - isolated
    ports:
      - "4200"


  eureka-server:
    restart: always
    container_name: eureka-server
    build:
      context: ../../eureka-server
    networks:
      - isolated
    ports:
      - "8081"
    environment:
      - eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
      - eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS}

  authorization-microservice:
    restart: always
    container_name: authorization-microservice
    build:
      context: ../../authorization-microservice
    depends_on:
      - kafka-file-manager
      - eureka-server
      - authorization-file-manager
    networks:
      - isolated
    ports:
      - "9200"
    environment:
      - spring.config.import=optional:file:./.env[.properties]
      - spring.datasource.username=${AUTHORIZATION_DATABASE_USERNAME}
      - spring.datasource.password=${AUTHORIZATION_DATABASE_PASSWORD}
      - spring.datasource.url=${AUTHORIZATION_DATABASE_URL}
      - spring.kafka.bootstrap-servers=${KAFKA_URL}
      - eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
      - eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS}
      - token.cookie.jwt.access-token.domain=${APPLICATION_DOMAIN}
      - token.cookie.jwt.access-token.name=${NAME_COOKIE_TOKEN_ACCESS_TOKEN}
      - token.cookie.jwt.access-token.secure=${COOKIE_SECURE}
      - token.cookie.jwt.access-token.sameSite=${COOKIE_SAME_SITE}
      - token.cookie.jwt.refresh-token.domain=${APPLICATION_DOMAIN}
      - token.cookie.jwt.refresh-token.name=${NAME_COOKIE_TOKEN_REFRESH_TOKEN}
      - token.cookie.jwt.refresh-token.secure=${COOKIE_SECURE}
      - token.cookie.jwt.refresh-token.sameSite=${COOKIE_SAME_SITE}


  file_manager:
    restart: always
    container_name: file_manager
    build:
      context: ../../file_manager
    depends_on:
      - kafka-file-manager
      - eureka-server
      - file-manager-file-system
    networks:
      - isolated
    ports:
      - "9000"
    environment:
      - spring.config.import=optional:file:./.env[.properties]
      - spring.datasource.username=${FILE_MANAGER_USERNAME}
      - spring.datasource.password=${FILE_MANAGER_PASSWORD}
      - spring.datasource.url=${FILE_MANAGER_DATABASE_URL}
      - spring.kafka.bootstrap-servers=${KAFKA_URL}
      - eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
      - eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS}
      - token.cookie.jwt.access-token.name=${NAME_COOKIE_TOKEN_ACCESS_TOKEN}
      - token.cookie.jwt.refresh-token.name=${NAME_COOKIE_TOKEN_REFRESH_TOKEN}
#      - logging.level.org.springframework=debug

  doc-service:
    restart: always
    container_name: doc-service
    build:
      context: ../../doc-service
    depends_on:
      - authorization-file-manager
      - file_manager
      - eureka-server
    networks:
      - isolated
    ports:
      - "8082"
    environment:
      - spring.config.import=optional:file:./.env[.properties]
      - spring.cloud.gateway.routes[0].id=authorization-microservice
      - spring.cloud.gateway.routes[0].uri=lb://authorization-microservice:9200
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/authorization-microservice/**
      - spring.cloud.gateway.routes[1].id=file-manager
      - spring.cloud.gateway.routes[1].uri=lb://file-manager:9000
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/file-manager/**
      - eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
      - eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS}

  zookeeper-file-manager:
    restart: always
    container_name: zookeeper-file-manager
    image: zookeeper:latest
    networks:
      - isolated
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - "2181"
    volumes:
      - ./zookeeper/data/datalog:/datalog
      - ./zookeeper/data/data:/data


  kafka-file-manager:
    restart: always
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper-file-manager
    networks:
      - isolated
    ports:
      - "29092"
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-file-manager:2181
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL_DIFFERENT_HOST://:29092,EXTERNAL_SAME_HOST://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-file-manager:9092,EXTERNAL_SAME_HOST://kafka-file-manager:9093,EXTERNAL_DIFFERENT_HOST://kafka-file-manager:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL_DIFFERENT_HOST:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


networks:
  isolated:
    internal: true
  net:
    driver: bridge
