server:
  port: 9000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/file_manager
    hikari:
      auto-commit: false


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: save-users-group
    topics:
      save:
        users: save-users

  servlet:
      multipart:
        max-file-size: 5GB
        max-request-size: 5GB

logging:
  level:
    org:
      springframework:
        security: info

service:
  authentication:
    is-authentication:
      url: api/authentication/micro-service/is-authentication
      protocol: http
      port: 9200
      host: localhost
