server:
  port: 9000

spring:

  profiles:
    active: default

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/file_manager
    hikari:
      auto-commit: false


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      group-id: save-users-group
    topics:
      save:
        users: save-users

  servlet:
      multipart:
        max-file-size: 5GB
        max-request-size: 5GB

  application:
    name: file-manager

token:
  cookie:
    jwt:
      access-token:
        name: __Host-access-token
      refresh-token:
        name: __Host-refresh-token

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

logging:
  level:
    org:
      springframework:
        security: debug

service:
  authentication:
    is-authentication:
      url: api/authentication/micro-service/is-authentication
      protocol: http
      port: 9200
      host: localhost

springdoc:
  api-docs:
    path: '/${spring.application.name}/v3/api-docs'
  swagger-ui:
    path: '/${spring.application.name}/swagger-ui.html'

path:
  default: ./src/main/resources/temp-files-for-download
